theme: jekyll-theme-minimal
logo: https://www.healthtech.dtu.dk/-/media/institutter/sundhedsteknologi/health-tech-newdesign/research/research-sections/bioinformatics/bioinformatics_graphic.jpg?rw=960&rh=0&hash=D4A1917E9829DB9BE4064403BD341192
title: Bioinformatics
